language: ruby
rvm:
- 2.6.3
before_script:
- chmod +x ./deploy.sh
script:
- bash ./deploy.sh
- ls -al
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - COMMIT_AUTHOR_EMAIL: alexandre.cuer@cerema.fr
  - ENCRYPTION_LABEL: 05e522b11dc9
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_05e522b11dc9_key -iv $encrypted_05e522b11dc9_iv
  -in dromotherm_rsa.enc -out dromotherm_rsa -d
